spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: wiki
    password: 123456
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true


mybatis:
  mapper-locations: classpath:org/jinjianou/project/wiki/mapper/*.xml
  type-aliases-package: org.jinjianou.project.wiki_knowledge_hub.domain
  configuration:
    map-underscore-to-camel-case: true